name: Lint

on: [push, pull_request]

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
          echo ::add-path::$(go env GOPATH)/bin # for Go projects

      - name: Install dependencies
        run: yarn install

      - name: textlint
        run: $(yarn bin)/textlint -f checkstyle ${FILES} | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review -level=${LEVEL}
        env:
          FILES: README.md docs/**/*.md
          LEVEL: error
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
